IO.puts([IO.ANSI.light_black(), "light_black"])
IO.puts([IO.ANSI.light_blue(), "light_blue"])
IO.puts([IO.ANSI.light_cyan(), "light_cyan"])
IO.puts([IO.ANSI.light_green(), "light_green"])
IO.puts([IO.ANSI.light_magenta(), "light_magenta"])
IO.puts([IO.ANSI.light_red(), "light_red"])
IO.puts([IO.ANSI.light_yellow(), "light_yellow"])
IO.puts([IO.ANSI.light_white(), "light_white"])

IO.puts([IO.ANSI.blue(), "blue"])
IO.puts([IO.ANSI.cyan(), "cyan"])
IO.puts([IO.ANSI.green(), "green"])
IO.puts([IO.ANSI.magenta(), "magenta"])
IO.puts([IO.ANSI.red(), "red"])
IO.puts([IO.ANSI.yellow(), "yellow"])
IO.puts([IO.ANSI.white(), "white"])
